id = "pico8-lua"
name = "PICO-8 Lua"
description = "Lua support for PICO-8 game development"
version = "0.1.2"
schema_version = 1
authors = ["Daniel Konar <dkonar@users.noreply.github.com>"]
repository = "https://github.com/dkonar/pico8-ls"

[language_servers.pico8-ls]
name = "PICO-8 LS"
language = "pico8"

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "a24dab177e58c9c6832f96b9a73102a0cfbced4a"
